### ISSUE TITLE
Null Pointer Exception in Knime PIA analysis using mzIdentml from Comet search results

### ISSUE THREAD

**Issue by thinkle12** [mpc-bioinformatics/pia#101] opened 2017-10-24 22:24 UTC
Hi, my name is Trent and I have been using PIA the past few weeks in attempt to generate some Protein Inference results from ms2 searches using Mascot and Comet. 
I have mostly been using the Knime workspace for protein inference but I would like to move to the command line version in the future with a custom param file as I would like to apply PIA to thousands of searches.

Anyway, I was wondering if you could provide any details on maybe why I am getting a Null Pointer Exception in Knime PIA Analysis and perhaps how I can access the more detailed error messages. I have attached the mzidentml from a comet search that generates the error to this issue called 130707-comet-edited.mzid (I am attaching a reduced version of this file as it is too large to attach here). I have also attached a Mascot mzidentml  which is able to generate good and expected protein inference results called 109691.mzid. 

I guess my question is why am I getting a Null Pointer Exception in Knime when I use the 130707-comet-edited.mzid (as it seems formatted properly - it was converted from a pepxml to a mzidentml using ProteoWizard). Also, through Knime I am not able to see the full Java Stack Trace error message, it simply says:
`ERROR PIA Analysis         6:11       Execute failed: ("NullPointerException"): null`
So, I am really not able to see the exact issue going on. Am I able to see the full Java Stack Trace error in Knime?

Finally, I was wondering if it is possible to get a PIA Parameter file from the Knime nodes? This would make it substantially easier to run PIA via command line as it seems daunting to create a custom parameter file from scratch. Debugging from the command line would also be easier than debugging through Knime as I would be able to see the full stdout and stderr.

I hope to hear back, thank you for your time.

Trent

Comet PIA Options:
![cometknimeoptions1](https://user-images.githubusercontent.com/5289095/31971042-151c83b6-b8cf-11e7-8e71-7a27e9bcfd2c.jpg)
![cometknimeoptions2](https://user-images.githubusercontent.com/5289095/31971043-15696b0e-b8cf-11e7-82ce-f54bf99c33df.jpg)
![cometknimeoptions3](https://user-images.githubusercontent.com/5289095/31971045-158da190-b8cf-11e7-8c78-f6df27e152be.jpg)
Mascot PIA Options
![mascotknimeoptions1](https://user-images.githubusercontent.com/5289095/31971046-15af8602-b8cf-11e7-948f-578e39e9cb28.jpg)
![mascotknimeoptions2](https://user-images.githubusercontent.com/5289095/31971047-15ca00c2-b8cf-11e7-8e1f-7c40168406ff.jpg)
![mascotknimeoptions3](https://user-images.githubusercontent.com/5289095/31971049-15eb9e3a-b8cf-11e7-823d-e4cf53b64331.jpg)
[comet_mzid.zip](https://github.com/mpc-bioinformatics/pia/files/1412683/comet_mzid.zip)
[mascot_mzid.zip](https://github.com/mpc-bioinformatics/pia/files/1412687/mascot_mzid.zip)

**Comment by ypriverol** [comment] 2017-10-24 22:28
Do you have problems only with the comet mzid file?. BTW, did you create the mzid comet file ?

**Comment by thinkle12** [comment] 2017-10-24 22:34
Correct, the Mascot mzid file works just fine, The Comet mzid file generates the null pointer exception error. I ran a search that generated a comet pepxml file. After that I used ProteoWizard to transform the comet pepxml file to a mzid file. I did the same thing with Mascot. Ideally I want to combine the search results of comet and mascot here but I am unable to get PIA to work with the comet results.

**Comment by ypriverol** [comment] 2017-10-25 00:21
I have tested the files with the latest version and it worrks perfectly well. I need to test the KNIME plugin now

**Comment by ypriverol** [comment] 2017-10-25 00:51
if you are interesting in the coding side, here the code: 

```java
public class ProteinInferenceMzIdentML {

    private File piaFile;
    private File piaMascotFile;
    private double scoreDelta = 0.000001;

    private String piaIntermediateFileName = "PIACompilerTest.pia.xml";


    @Before
    public void setUp() throws URISyntaxException {
        piaFile = new File(ReportProteinTest.class.getClassLoader().getResource("test/130707-comet-edited.mzid").toURI());
        piaMascotFile = new File(ReportProteinTest.class.getClassLoader().getResource("test/109691.mzid").toURI());
    }


    @Test
    public void testReportProteinValues() throws JAXBException, XMLStreamException, IOException, URISyntaxException {

        PIACompiler piaCompiler = new PIASimpleCompiler();

        assertEquals(true, piaCompiler.getDataFromFile("comet", piaFile.getAbsolutePath(), null, null));
        assertEquals(true, piaCompiler.getDataFromFile("mascot", piaMascotFile.getAbsolutePath(), null, null));

        piaCompiler.buildClusterList();
        piaCompiler.buildIntermediateStructure();

        piaCompiler.setName("testFile");


        // write out the file
        File piaIntermediateFile = File.createTempFile(piaIntermediateFileName, null);
        piaCompiler.writeOutXML(piaIntermediateFile);
        piaCompiler.finish();

        // now make an analysis
        PIAModeller piaModeller = new PIAModeller(piaIntermediateFile.getAbsolutePath());


        piaModeller.setCreatePSMSets(true);

        piaModeller.getPSMModeller().setAllDecoyPattern("##.*");
        piaModeller.getPSMModeller().setAllTopIdentifications(0);

        piaModeller.getPSMModeller().calculateAllFDR();
        piaModeller.getPSMModeller().calculateCombinedFDRScore();

        piaModeller.setConsiderModifications(false);

        // protein level
        SpectrumExtractorInference seInference = new SpectrumExtractorInference();

        seInference.addFilter(
                new PSMScoreFilter(FilterComparator.less_equal, false, 0.01, ScoreModelEnum.PSM_LEVEL_FDR_SCORE.getShortName()));

        seInference.setScoring(new MultiplicativeScoring(new HashMap<>()));
        seInference.getScoring().setSetting(AbstractScoring.SCORING_SETTING_ID, ScoreModelEnum.PSM_LEVEL_FDR_SCORE.getShortName());
        seInference.getScoring().setSetting(AbstractScoring.SCORING_SPECTRA_SETTING_ID, PSMForScoring.ONLY_BEST.getShortName());

        piaModeller.getProteinModeller().infereProteins(seInference);

        piaModeller.getProteinModeller().updateFDRData(FDRData.DecoyStrategy.ACCESSIONPATTERN, "s.*", 0.01);
        piaModeller.getProteinModeller().updateDecoyStates();
        piaModeller.getProteinModeller().calculateFDR();


        List<AbstractFilter> filters = new ArrayList<>();
        filters.add(RegisteredFilters.NR_GROUP_UNIQUE_PEPTIDES_PER_PROTEIN_FILTER.newInstanceOf(
                FilterComparator.greater_equal, 2, false));


        // get the expected values
        Map<String, List<Object>> expectedValues = new HashMap<>(426);

        List<ReportProtein> proteins = piaModeller.getProteinModeller().getFilteredReportProteins(filters);
        // compare the values
        for (ReportProtein prot : proteins) {
            StringBuilder accSb = new StringBuilder();
            for (Accession acc : prot.getAccessions()) {
                accSb.append(acc.getAccession());
                accSb.append(",");
            }
            accSb.deleteCharAt(accSb.length()-1);

            List<Object> values = expectedValues.get(accSb.toString());
            assertNotNull("These accessions are not expected: " + accSb.toString(), values);

            assertEquals("Wrong score for " + accSb.toString(), (Double)(values.get(0)), prot.getScore(), scoreDelta);
            assertEquals("Wrong number of peptides for " + accSb.toString(), values.get(1), prot.getNrPeptides());
            assertEquals("Wrong number of PSMs for " + accSb.toString(), values.get(2), prot.getNrPSMs());
            assertEquals("Wrong number of spectra for " + accSb.toString(), values.get(3), prot.getNrSpectra());
            assertEquals("Wrong decoy state for " + accSb.toString(), values.get(4), prot.getIsDecoy());
            assertEquals("Wrong FDR for " + accSb.toString(), (Double)(values.get(5)), prot.getFDR(), scoreDelta);
            assertEquals("Wrong q-value for " + accSb.toString(), (Double)(values.get(6)), prot.getQValue(), scoreDelta);
        }
    }
}

```

**Comment by thinkle12** [comment] 2017-10-25 01:50
We're you able to get the file to work with Knime?
Also could you potentially provide the pia parameter file you used to make PIA work via command line?

**Comment by julianu** [comment] 2017-10-25 06:05
Hi, the KNIME nodes are not up-to-date currently, but I am working on an update, which should be out in a few days.
But I will also have a look at your file in the development version and see, what exactly causes the error.

**Comment by julianu** [comment] 2017-10-25 06:14
BTW: I was thinking about creating a param-file-creation-node or somthing, which writes out the param file for command line usage from KNIME. Do you mind creating a new "enhancement" issue?

**Comment by julianu** [comment] 2017-10-25 09:22
Update: I can reproduce the error in the KNIME-node and will have a look, where this exception is thrown.

**Comment by julianu** [comment] 2017-10-27 08:36
Update2: I think I found the problem: in the stable KNIME nodes, the comet-scores don't get parsed for some reason. Having no score and trying to get them gives the Null-Pointer (not a nice error message, fill fix that as well).

Unfortunately, there is also some issue with the jmzIdenML library I am currently using in the development-version. It is a bit slow (meaning: reading in the mzId files takes ages, probably due to some misconfigured indexing at some place).

I am at this as well, but won't have much time until end of next week. Please stand by...

**Comment by thinkle12** [comment] 2017-10-27 18:26
I have noticed something when using PIA on command line. It seems that when the mzid is compiled to a pia.xml that some of the scores are passed to `Score` and others are passed to `userParam`
Here is an example from a pia.xml from a mascot search with percolator

    
``` <spectrumMatch charge="2" deltaMass="-0.004878999999959888" fileRef="1" id="6" massToCharge="300.70515446688" missed="0" sequence="VQLIK" spectrumIdentificationRef="specIdent_1_1">
      <sourceID>111323.6347.6347.2.dta</sourceID>
      <Score cvAccession="MS:1001171" name="Mascot Ion Score" value="24.22"/>
      <Score cvAccession="MS:1001371" name="Mascot:identity threshold" value="37.0"/>
      <Score cvAccession="MS:1001370" name="Mascot:homology threshold" value="32.0"/>
      <Score cvAccession="MS:1001172" name="Mascot Expect" value="1.1"/>
      <cvParam cvRef="MS" accession="MS:1001121" name="number of matched peaks" value="4"/>
      <userParam name="percolator:Q value" value="0.048853"/>
      <userParam name="percolator:PEP" value="0.432392"/>
      <userParam name="search_id" value="1"/>
    </spectrumMatch>```

Here is an example from a pia.xml from a comet search

```
 <spectrumMatch charge="2" deltaMass="-0.010198999999943226" fileRef="1" id="16" massToCharge="453.72162696688" missed="0" sequen$
      <sourceID>111323.1678.1678.2.dta</sourceID>
      <Modification location="4" mass="57.0214645222" residue="C"/>
      <cvParam cvRef="MS" accession="MS:1001121" name="number of matched peaks" value="2"/>
      <cvParam cvRef="MS" accession="MS:1001362" name="number of unmatched peaks" value="14"/>
      <userParam name="xcorr" value="0.476"/>
      <userParam name="deltacn" value="0.015"/>
      <userParam name="deltacnstar" value="0.000"/>
      <userParam name="spscore" value="17.1"/>
      <userParam name="sprank" value="2"/>
      <userParam name="expect" value="7.60E+00"/>
    </spectrumMatch>```

Is this something to do with the fact that the mascot scores have accessions?
When I go in and manually change `userParam` to `Score`, I see that I am able to get it to work via the command line. Now I am just concerned why it is calling my scores `userParam` instead of `Score`.
I have attempted to write a parser that parses the pia.xml and changes the name from `userParam` to `Score` (Instead of manually which worked). However, when I do this I get the following error:
```
[27-Oct-2017 10:42:29 - ERROR] "Error parsing command line" (de.mpc.pia.modeller.PIAModeller:820)
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -paramfile
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:702)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:533)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at de.mpc.pia.modeller.PIAModeller.main(PIAModeller.java:810)
usage: PIAModeller [-append] [-calculateInformation <outfile>] [-E
       <command1[:command2...]>] [-execute] [-infile <inputFile>] [-init
       <name>] [-paramFile <filename>] [-paramOutFile <filename>]
       [-peptideExport <outfile format [fileID=ID] [exportPSMs=true/false]
       [exportPSMSets=true/false] [oneAccessionPerLine=true/false]>]
       [-proteinExport <outfile format [exportPSMs=true/false]
       [exportPSMSets=true/false] [exportPeptides=true/false]
       [oneAccessionPerLine=true/false]
       [exportProteinSequences=true/false]>] [-psmExport <outfile format
       [fileID=ID] [spectralCount=true/false]>] [-R
       <command1[:command2...]>] [-S <command1[:command2...]>]
       [-writeInformation <outfile>]```

**Comment by julianu** [comment] 2017-10-28 12:05
Yes, that's exactly the problem I meant above: the stable version of PIA does not yet recognize all the scores, although it obviously should. It still tries to fetch all data of the PSM, thus some unrecognized scores become userParams.
Anyways, fixing this should be relatively straight forward. I will attend to a conference from tomorrow until midweek though... maybe I find some time to fix this there, otherwise as soon as I am back.

**Comment by thinkle12** [comment] 2017-10-30 16:00
Great, thank you so much I really appreciate you taking the time to help me out. I am really hoping to use Percolator scores, Comet scores, and Mascot scores.

**Comment by julianu** [comment] 2017-10-30 22:03
Jepp, thought so @ypriverol. Usually, PIA should pick up all kinds of spectrum ID scores from mzIdentML automagically, though. Maybe something is missing there, I will investigate that as well. 
Then, I just need to put it into the KNIME nodes and hope, that I get a new release there soon. I will inform you, as soon as I sorted all out.

**Comment by thinkle12** [comment] 2017-10-30 22:05
So, is the update available in the command line version currently?

**Comment by julianu** [comment] 2017-10-31 05:35
Only if you compile the source, I am afraid. And there is this problem with the slow mzIdentML implementation currently. I will make a new release of the command line version at the end of this week, which should hopefully work with your files.

**Comment by thinkle12** [comment] 2017-10-31 18:04
Great, thank you for this.
Here are some test mzidentML files if you need any. One of the files has mascot and percolator scores, the other has comet scores.
https://nofile.io/f/vtZE568dzA5/130707-comet.mzid
https://nofile.io/f/fzXRzhmrFNw/mascot_and_percolator_scores.mzid

Also, I think it would be very beneficial for users if this page was updated with all of the score names:
https://github.com/mpc-bioinformatics/pia/wiki/Score-Names

finally, I am still slightly confused with naming conventions, for example in my mzid files do I need certain scores to be a specific string? Meaning should they be the internal short name or the long name?

**Comment by julianu** [comment] 2017-11-02 15:45
Ok, the parsing of your files is now working.
The problem was that actually all Comet scores were "userParams" instead of "cvParams", which is probably a problem of ProteoWizard. Did you use the newest version? If so, they should update their CV-ontology versions.
Anyways, both files work now. And if you want to process the Comet files with percolator as well, that should also work (if the naming is consistent). I will make a new release tomorrow.

Updating the wiki is a good idea, right... will do so. Actually, it is also possible to use other scores for FDR calculation etc. using the accession number of the PSI CV (like 1001171 for the Mascot ion score). I will try to add that.

The naming in the mzid files does not necessarily need to follow the naming conventions in the PIA XML files, no. Especially the short and long names are only used in PIA and are also hard-coded for mzid import and export to the correct accessions. If you ever want to generate semantically correct mzid files, you should write out the scores etc. as cvParams, if possible. To "register" anything into the controlled vocabulary, you only need to ask @germa .

Would it be ok for you, if i used a (even more edited) version of you file in the repository for CI testing?

**Comment by thinkle12** [comment] 2017-11-02 19:01
Awesome thank you. 
I believe I used the newest version of ProteoWizard...
So correct me if I am wrong but will I need to edit the mzid's to have the Comet and Percolator scores be called "cvParams" with proper accession numbers? Or will it work with them as "userParams" now too without accession numbers?
And yes you can certainly use my file in the repository for CI testing.

**Comment by julianu** [comment] 2017-11-03 08:07
Hej @thinkle12, you should not have to edit the mzid files at all, no. PIA will take care of it and also parse the userParams as scores. Actually, if exporting into mzId again, they should become cvParams, if they are in the CV (and I included them in the set of known scores).

Anyways, this looks like a different error. Could you try again with an not-edited direct ProteoWizard export and if the error remains share the file here?

**Comment by thinkle12** [comment] 2017-11-07 18:29
Hi @julianu, The percolator scores are not being parsed every time... For example the file:
https://nofile.io/f/07m2GJaEWef/130707-comet-perc.pep.mzid
Is a comet mzid with comet and percolator scores as follows:
```
<SpectrumIdentificationItem id="SII_35848" rank="4" chargeState="2" peptide_ref="PEP_34052" experimentalMassToCharge="505.77640546688" calculatedMassToCharge="505.77621196688" passThreshold="true">
            <PeptideEvidenceRef peptideEvidence_ref="##sp|RL13_HUMAN|P26373_PEP_34052"/>
            <cvParam cvRef="MS" accession="MS:1001121" name="number of matched peaks" value="3"/>
            <cvParam cvRef="MS" accession="MS:1001362" name="number of unmatched peaks" value="13"/>
            <userParam name="xcorr" value="0.666" type="xsd:float"/>
            <userParam name="deltacn" value="0.144" type="xsd:float"/>
            <userParam name="deltacnstar" value="0.000" type="xsd:float"/>
            <userParam name="spscore" value="24.8" type="xsd:float"/>
            <userParam name="sprank" value="10" type="xsd:float"/>
            <userParam name="expect" value="3.80E+01" type="xsd:float"/>
            <userParam name="percolator:Q value" value="0.694259" type="xsd:float"/>
            <userParam name="percolator:PEP" value="0.896624" type="xsd:float"/>
          </SpectrumIdentificationItem>
```
As we can see they are all userParams...
I ran the following command:
`java -Xmx6G -cp pia-1.3.5.jar de.mpc.pia.intermediate.compiler.PIACompiler -infile 130707-comet-perc.pep.mzid -name "name of compilation" -outfile comet_perc.pia.xml`

https://nofile.io/f/sMav9bsAgPA/comet_perc.pia.xml
The outfile looks as follows
```    
<spectrumMatch charge="2" deltaMass="-0.010797000000025037" fileRef="1" id="1" massToCharge="453.72132796688" missed="0" sequence="LASCAASAR" spectrumIdentificationRef="specIdent_1_1">
      <sourceID>111323.1228.1228.2.dta</sourceID>
      <Score cvAccession="MS:1002252" name="Comet:xcorr" value="0.463"/>
      <Score cvAccession="MS:1002253" name="Comet:deltacn" value="0.056"/>
      <Score cvAccession="MS:1002254" name="Comet:deltacnstar" value="0.0"/>
      <Score cvAccession="MS:1002255" name="Comet:spscore" value="13.7"/>
      <Score cvAccession="MS:1002256" name="Comet:sprank" value="2.0"/>
      <Score cvAccession="MS:1002257" name="Comet:expectation value" value="2.33"/>
      <Modification location="4" mass="57.0214645222" residue="C"/>
      <cvParam cvRef="MS" accession="MS:1001121" name="number of matched peaks" value="2"/>
      <cvParam cvRef="MS" accession="MS:1001362" name="number of unmatched peaks" value="14"/>
      <userParam name="percolator:Q value" value="0.700627"/>
      <userParam name="percolator:PEP" value="0.896624"/>
    </spectrumMatch>
```

So it seems to be parsing the comet scores but not the percolator scores now..

**Comment by julianu** [comment] 2017-11-08 15:49
Ok, so is the provided file at https://nofile.io/f/sMav9bsAgPA/comet_perc.pia.xml an unedited comet output, meaning the output of ProteoWizard? I assumed the same naming as from the Mascot example, but looks like it's different.
Anyways, it is no problem to adjust the parser to work correctly with this. I will do so ASAP, probably beginning of next week though.

**Comment by thinkle12** [comment] 2017-11-08 21:24
Yes, the file is unedited out of ProteoWizard... But I realized my naming convention was incorrect I needed to use "Q value" and "PEP" but I used "percolator:Q value" and "percolator:PEP". Simply was a naming convention issue which I fixed

**Comment by thinkle12** [comment] 2017-11-08 21:44
I did have another issue with filesize now actually... I am unable to bypass the following error with this file:
https://nofile.io/f/uDVcQFGzbGv/130835-comet-with-perc.mzid
```
hinklet-10GYFH:pia-1.3.5 hinklet$ java -Xmx6G -cp pia-1.3.5.jar de.mpc.pia.intermediate.compiler.PIACompiler -infile /Users/hinklet/PythonFiles/other/130835-comet-with-perc.mzid -outfile 130835-comet-with-perc.pia.xml
[08-Nov-2017 11:22:20 - INFO] "file: /Users/hinklet/PythonFiles/other/130835-comet-with-perc.mzid
	name: 130835-comet-with-perc.mzid
	type: null
	additional info file: null" (de.mpc.pia.intermediate.compiler.PIACompiler:1333)
[08-Nov-2017 11:22:20 - INFO] "'/Users/hinklet/PythonFiles/other/130835-comet-with-perc.mzid' seems to be a mzIdentML file" (de.mpc.pia.intermediate.compiler.parser.InputFileParserFactory:373)
[08-Nov-2017 11:22:20 - WARN] "MzIdentML Configuration file: jar:file:/Users/hinklet/Downloads/pia-1.3.5/lib/jmztab-modular-converters-3.0.7.jar!/MzIdentMLElement.cfg.xml" (uk.ac.ebi.jmzidml.MzIdentMLElement:1100)
[08-Nov-2017 11:22:20 - WARN] "MzIdentML Configuration file: jar:file:/Users/hinklet/Downloads/pia-1.3.5/lib/jmztab-modular-converters-3.0.7.jar!/MzIdentMLElement.cfg.xml" (uk.ac.ebi.jmzidml.MzIdentMLElement:1100)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hinklet/Downloads/pia-1.3.5/lib/log4j-slf4j-impl-2.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hinklet/Downloads/pia-1.3.5/lib/logback-classic-0.9.24.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at uk.ac.ebi.jmzidml.xml.jaxb.unmarshaller.filters.MzIdentMLNamespaceFilter.startElement(MzIdentMLNamespaceFilter.java:35)
	at com.ctc.wstx.sr.BasicStreamReader.fireSaxStartElement(BasicStreamReader.java:1705)
	at com.ctc.wstx.sax.WstxSAXParser.fireStartTag(WstxSAXParser.java:720)
	at com.ctc.wstx.sax.WstxSAXParser.fireEvents(WstxSAXParser.java:605)
	at com.ctc.wstx.sax.WstxSAXParser.parse(WstxSAXParser.java:537)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:273)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.AbstractReferenceResolver.unmarshal(AbstractReferenceResolver.java:88)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.DBSequenceRefResolver.updateObject(DBSequenceRefResolver.java:25)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.DBSequenceRefResolver.afterUnmarshal(DBSequenceRefResolver.java:40)
	at uk.ac.ebi.jmzidml.xml.jaxb.unmarshaller.listeners.RawXMLListener.referenceResolving(RawXMLListener.java:187)
	at uk.ac.ebi.jmzidml.xml.jaxb.unmarshaller.listeners.RawXMLListener.afterUnmarshal(RawXMLListener.java:52)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.fireAfterUnmarshal(Loader.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.leaveElement(StructureLoader.java:265)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:585)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:165)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.ctc.wstx.sr.BasicStreamReader.fireSaxEndElement(BasicStreamReader.java:1719)
	at com.ctc.wstx.sax.WstxSAXParser.fireEvents(WstxSAXParser.java:614)
	at com.ctc.wstx.sax.WstxSAXParser.parse(WstxSAXParser.java:537)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:273)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.AbstractReferenceResolver.unmarshal(AbstractReferenceResolver.java:88)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.PeptideEvidenceResolver.updateObject(PeptideEvidenceResolver.java:27)
	at uk.ac.ebi.jmzidml.xml.jaxb.resolver.PeptideEvidenceResolver.afterUnmarshal(PeptideEvidenceResolver.java:54)
```

Is the file simply too large? and could increasing -Xmx6G to a larger value help?

**Comment by julianu** [comment] 2017-11-09 18:02
First to your previous comment: you said your naming convention was wrong? So, if you are putting the percolator scores into the mzid files, you should definitely use the cvParams with correct accessions and names. Otherwise: I will adjust the parser to work with the file provided.

Next: PIA is very memory hungry at the moment, yes. So, giving it enough memory is always good, also to speed things up (Java's garbage collection etc. are slow, if called all the time). Actually, I would recommend at least 8GB, if you can spare it. Or, too make it as fast as possible, as much as you can^^
It worked though also with some 270 searches (3 search engines and 90 MS files, human database) with enough memory - this was 128GB though. Anyways, I have some plans to make it less memory hungry, if time permits the development.

Finally: The new error needs some inspection and time. Will try to do this next week.

**Comment by thinkle12** [comment] 2017-11-10 22:14
Thanks for the reply, I actually got all the PIA runs to go through thankfully by increasing the memory which is good (They still took a long time to work but at least they went through). 

The new error is less important seeing as I can actually get the runs to go through with the large files (The reason I attempted the run with only rank 1 information in the mzid in the first place was because I couldn't get the larger files to run). But now that I can get the runs to work with increasing the memory the latter error because less important.

**Comment by julianu** [comment] 2017-11-29 08:46
Hej @thinkle12,
regarding the error in your post before the last one: I cannot reproduce it with the file you sent me.
But is it anyway still a problem, as you were able to use the file containing all identifications? If it is no problem any more, I will close this bug.

**Closed** 2018-05-23 14:57 UTC
Labels: bug
